version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Pre-build phase...
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t fileferry-agent .
  post_build:
    commands:
      - echo Post-build phase...
      - echo Pushing the Docker image to ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - docker tag fileferry-agent:latest <your_ecr_repository_uri>:latest
      - docker push <your_ecr_repository_uri>:latest
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: build_output