AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FileFerry Lambda Functions and Step Functions

Globals:
  Function:
    Runtime: python3.11
    Timeout: 300
    MemorySize: 512
    Environment:
      Variables:
        DYNAMODB_TABLE: FileFerry-Transfers

Resources:
  ValidateInputFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FileFerry-ValidateInput
      CodeUri: ./
      Handler: validate_input.lambda_handler
      Role: arn:aws:iam::637423332185:role/FileFerryLambdaExecutionRole

  AuthSSOFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FileFerry-AuthSSO
      CodeUri: ./
      Handler: auth_sso.lambda_handler
      Role: arn:aws:iam::637423332185:role/FileFerryLambdaExecutionRole

  DownloadS3Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FileFerry-DownloadS3
      CodeUri: ./
      Handler: download_s3.lambda_handler
      Role: arn:aws:iam::637423332185:role/FileFerryLambdaExecutionRole

  TransferFTPFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FileFerry-TransferFTP
      CodeUri: ./
      Handler: transfer_ftp.lambda_handler
      Role: arn:aws:iam::637423332185:role/FileFerryLambdaExecutionRole

  ChunkedTransferFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FileFerry-ChunkedTransfer
      CodeUri: ./
      Handler: chunked_transfer.lambda_handler
      Role: arn:aws:iam::637423332185:role/FileFerryLambdaExecutionRole

  UpdateServiceNowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FileFerry-UpdateServiceNow
      CodeUri: ./
      Handler: update_servicenow.lambda_handler
      Role: arn:aws:iam::637423332185:role/FileFerryLambdaExecutionRole

  NotifyUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FileFerry-NotifyUser
      CodeUri: ./
      Handler: notify_user.lambda_handler
      Role: arn:aws:iam::637423332185:role/FileFerryLambdaExecutionRole

  CleanupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FileFerry-Cleanup
      CodeUri: ./
      Handler: cleanup.lambda_handler
      Role: arn:aws:iam::637423332185:role/FileFerryLambdaExecutionRole

  FileFerryStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: FileFerry-TransferStateMachine
      DefinitionUri: step_functions_state_machine.json
      Role: arn:aws:iam::637423332185:role/FileFerryStepFunctionsRole

Outputs:
  StateMachineArn:
    Description: ARN of the Step Functions state machine
    Value: !Ref FileFerryStateMachine
